export default{
    MARK_NOTIFICATION_AS_READ_BY_ID:"MARK_NOTIFICATION_AS_READ_BY_ID",
    MARK_ALL_NOTIFICATIONS_AS_READ:"MARK_ALL_NOTIFICATIONS_AS_READ",
    Begin_MARK:"Begin_MARK",
    END_MARK:"END_MARK",
    RECEIVE_NOTIFICATION:"RECEIVE_NOTIFICATION",
    START_lOG:"START_lOG",
    LOG_SUCCESS:"LOG_SUCCESS",
    LOG_FAIL:"LOG_FAIL",
    LOG_OUT:  "LOG_OUT",
    AVATAR_UPLOAD:"AVATAR_UPLOAD"
}